### PR TITLE
[bookmarklet] Work For One Commit Fix

### PR DESCRIPTION
**Pull request by sncraig01**
# Description

Makes the bookmarklet work when the PR only has one commit!

It should be slightly more robust as it pulls the branch name from this selector as opposed to the auto-generated pr title

Screenshot 2024-04-01 at 3 36 37 PM

### CODE REVIEW

**Review by chrislonge — APPROVED** [review]
LGTM! Thanks for the enhancement!

**Review by chrislonge — COMMENTED** [review]
BTW, I'm curious how you generated the bookmarklet part?

**Review by SebastianHelzer — APPROVED** [review]
LGTM. This feels like something that could be tested rather easily with a collection of branch names.

**Comment by chrislonge** [comment]
> LGTM. This feels like something that could be tested rather easily with a collection of branch names.

@SebastianHelzer, are you interested in contributing a small test suite contribution? 😜 Joking aside, I do think it would probably be easy to add a small unit test suite.

**Pull request merged**
